name: Build & Deploy Nuxt

on:
  push:
    branches:
      - master

concurrency:
  group: nuxt-pages-deploy
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Generate static site
        run: pnpm generate
        env:
          NUXT_BASE_URL: /
          NUXT_PUBLIC_DOMAINL: code-creeper.github.io

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: .output/public
          publish_branch: gh-pages